spring.application.name=SimpleSpringProject

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/PersonDB
spring.r2dbc.username=postgres
spring.r2dbc.password=7899

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.root=INFO
logging.level.com.example.simplespringproject=DEBUG
logging.file.name=logs/app.log