spring.application.name=SimpleSpringProject
server.port=8082
spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.root=INFO
logging.level.com.example.simplespringproject=DEBUG
logging.file.name=logs/app.log